import { StyleSheet } from 'react-native';

export const BUTTON_SHADOW_OFFSET = 5;

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#02060a',
  },
  loadingScreen: {
    flex: 1,
    backgroundColor: '#02060a',
  },
  mainColumn: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 6,
    gap: 10,
    position: 'relative',
    zIndex: 2,
  },
  logoWrap: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 2,
  },
  logoImage: {
    marginTop: 18,
    marginBottom: 4,
    width: 300,
    height: 96,
  },
  topTagline: {
    fontFamily: 'Jersey10_400Regular',
    color: '#e6e8ec',
    fontSize: 19,
    lineHeight: 18,
    letterSpacing: 1.6,
    marginBottom: 9,
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  qualifiedPill: {
    width: '95%',
    maxWidth: 360,
    borderWidth: 3,
    borderColor: '#b82a69',
    borderRadius: 14,
    backgroundColor: '#04090d',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 9,
    paddingHorizontal: 16,
    gap: 10,
    marginBottom: 4,
    position: 'relative',
    overflow: 'visible',
  },
  qualifiedEar: {
    position: 'absolute',
    top: '50%',
    width: 5,
    height: 18,
    marginTop: -9,
    borderColor: '#6f8f4f',
    backgroundColor: '#050b0e',
    borderTopWidth: 2,
    borderBottomWidth: 2,
  },
  qualifiedEarLeft: {
    left: -8,
    borderLeftWidth: 2,
  },
  qualifiedEarRight: {
    right: -8,
    borderRightWidth: 2,
  },
  qualifiedIconWrap: {
    width: 26,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qualifiedText: {
    fontFamily: 'Jersey10_400Regular',
    color: '#81f33c',
    fontSize: 46,
    lineHeight: 34,
    letterSpacing: 0.6,
    textShadowColor: 'rgba(129, 243, 60, 0.24)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  batteryPanel: {
    width: '95%',
    maxWidth: 360,
    borderWidth: 3,
    borderColor: '#6f8f4b',
    borderRadius: 14,
    paddingTop: 16,
    paddingBottom: 10,
    alignItems: 'center',
    backgroundColor: '#03080c',
    marginBottom: 6,
  },
  batteryWrap: {
    width: '88%',
    maxWidth: 300,
    height: 114,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  batteryBody: {
    flex: 1,
    height: '100%',
    borderColor: '#8efe58',
    borderWidth: 6,
    backgroundColor: '#04080b',
    position: 'relative',
    overflow: 'hidden',
  },
  batteryTip: {
    width: 18,
    height: 56,
    borderTopWidth: 6,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    borderColor: '#8efe58',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    backgroundColor: '#071108',
  },
  batteryTipLine: {
    width: '64%',
    height: 2,
    backgroundColor: '#2f5d2a',
  },
  batteryVerticalLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(103, 255, 86, 0.14)',
  },
  batteryHorizontalLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(103, 255, 86, 0.11)',
  },
  batteryFill: {
    position: 'absolute',
    top: 8,
    bottom: 8,
    left: 8,
    backgroundColor: '#ff2d35',
  },
  percentText: {
    fontFamily: 'Jersey10_400Regular',
    color: '#ff4a67',
    fontSize: 98,
    lineHeight: 80,
    letterSpacing: 2.2,
    marginTop: 4,
    textShadowColor: 'rgba(255, 74, 103, 0.32)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  powerRemainingText: {
    fontFamily: 'Jersey10_400Regular',
    color: '#f1f5f8',
    fontSize: 22,
    lineHeight: 18,
    marginTop: 1,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.45)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 3,
  },
  accessPanel: {
    width: '95%',
    maxWidth: 360,
    borderWidth: 3,
    borderColor: '#b82a69',
    borderRadius: 14,
    backgroundColor: '#04090d',
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 8,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  accessCopy: {
    flex: 1,
    paddingRight: 8,
  },
  accessPanelTitle: {
    fontFamily: 'Jersey10_400Regular',
    color: '#82f33e',
    fontSize: 54,
    lineHeight: 39,
    letterSpacing: 0.9,
  },
  accessPanelDivider: {
    marginTop: 4,
    marginBottom: 6,
    height: 1,
    width: '100%',
    backgroundColor: 'rgba(213, 214, 219, 0.15)',
  },
  accessPanelText: {
    fontFamily: 'Jersey10_400Regular',
    color: '#f1f5f8',
    fontSize: 22,
    lineHeight: 21,
    letterSpacing: 1.2,
  },
  operatorSpriteWrap: {
    width: 90,
    height: 106,
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    marginLeft: 8,
  },
  operatorImage: {
    width: 86,
    height: 104,
  },
  bottomButtonsDock: {
    width: '95%',
    maxWidth: 360,
    marginTop: 7,
    paddingBottom: 8,
  },
  actionButtonWrapper: {
    width: '100%',
    marginTop: 0,
    paddingRight: BUTTON_SHADOW_OFFSET,
    paddingBottom: BUTTON_SHADOW_OFFSET,
  },
  actionButtonShadow: {
    position: 'absolute',
    top: BUTTON_SHADOW_OFFSET,
    left: BUTTON_SHADOW_OFFSET,
    right: 0,
    bottom: 0,
    backgroundColor: '#224614',
    borderRadius: 16,
  },
  actionButtonPressable: {
    width: '100%',
  },
  actionButtonFace: {
    width: '100%',
    borderWidth: 3,
    borderColor: '#83f640',
    borderRadius: 16,
    backgroundColor: '#0d2608',
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonText: {
    fontFamily: 'Jersey10_400Regular',
    color: '#83f640',
    fontSize: 64,
    lineHeight: 46,
    letterSpacing: 1.4,
    textAlign: 'center',
    textShadowColor: 'rgba(131, 246, 64, 0.24)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  howToButtonWrapper: {
    marginTop: 9,
    maxWidth: 286,
    alignSelf: 'center',
  },
  howToButtonShadow: {
    backgroundColor: '#3b1d56',
    borderRadius: 10,
  },
  howToButtonFace: {
    borderColor: '#8f44c7',
    borderRadius: 10,
    backgroundColor: '#0b0820',
    paddingVertical: 8,
  },
  howToButtonText: {
    color: '#d9c0ee',
    fontSize: 38,
    lineHeight: 26,
    letterSpacing: 1.4,
  },
  pixelRow: {
    flexDirection: 'row',
  },
  pixelCell: {
    borderWidth: 0,
  },
  scanline: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: '#08140a',
  },
  scanlineOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  phosphorTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(35, 255, 55, 0.04)',
    zIndex: 1,
  },
  vignette: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.18)',
    zIndex: 1,
  },
});
