import { StyleSheet } from 'react-native';

export const BUTTON_SHADOW_OFFSET = 5;

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#02060a',
  },
  loadingScreen: {
    flex: 1,
    backgroundColor: '#02060a',
  },
  mainColumn: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 8,
    gap: 0,
    position: 'relative',
    zIndex: 2,
  },
  logoWrap: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 2,
  },
  logoImage: {
    marginTop: 18,
    marginBottom: 6,
    width: 336,
    height: 108,
  },
  centerCluster: {
    width: '100%',
    flex: 1,
    minHeight: 0,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },
  qualifiedPill: {
    width: '89%',
    borderWidth: 3,
    borderColor: '#b82a69',
    borderRadius: 14,
    backgroundColor: '#04090d',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 50,
    paddingHorizontal: 14,
    position: 'absolute',
    top: -25,
    alignSelf: 'center',
    zIndex: 3,
    overflow: 'visible',
  },
  qualifiedEar: {
    position: 'absolute',
    top: '50%',
    width: 5,
    height: 18,
    borderColor: '#6f8f4f',
    backgroundColor: '#050b0e',
    borderTopWidth: 2,
    borderBottomWidth: 2,
    transform: [{ translateY: -9 }],
  },
  qualifiedEarLeft: {
    left: -8,
    borderLeftWidth: 2,
  },
  qualifiedEarRight: {
    right: -8,
    borderRightWidth: 2,
  },
  qualifiedText: {
    fontFamily: 'Jersey10_400Regular',
    color: '#81f33c',
    fontSize: 34,
    lineHeight: 34,
    letterSpacing: 0.5,
    textAlignVertical: 'center',
    marginTop: 1,
    textShadowColor: 'rgba(129, 243, 60, 0.24)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  batteryPanel: {
    width: '95%',
    maxWidth: 360,
    borderWidth: 3,
    borderColor: '#6f8f4b',
    borderRadius: 14,
    paddingTop: 34,
    paddingBottom: 10,
    alignItems: 'center',
    backgroundColor: '#03080c',
    marginBottom: 0,
    marginTop: 0,
    position: 'relative',
  },
  batteryWrap: {
    width: '88%',
    maxWidth: 300,
    height: 108,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  batteryBody: {
    flex: 1,
    height: '100%',
    borderColor: '#8efe58',
    borderWidth: 6,
    backgroundColor: '#04080b',
    position: 'relative',
    overflow: 'hidden',
  },
  batteryTip: {
    width: 18,
    height: 56,
    borderTopWidth: 6,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    borderColor: '#8efe58',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    backgroundColor: '#071108',
  },
  batteryTipLine: {
    width: '64%',
    height: 2,
    backgroundColor: '#2f5d2a',
  },
  batteryVerticalLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(103, 255, 86, 0.14)',
  },
  batteryHorizontalLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(103, 255, 86, 0.11)',
  },
  batteryFill: {
    position: 'absolute',
    top: 8,
    bottom: 8,
    left: 8,
    backgroundColor: '#ff2d35',
  },
  percentText: {
    fontFamily: 'Jersey10_400Regular',
    color: '#ff4a67',
    fontSize: 94,
    lineHeight: 76,
    letterSpacing: 2.2,
    marginTop: 4,
    textShadowColor: 'rgba(255, 74, 103, 0.32)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  powerRemainingText: {
    fontFamily: 'Jersey10_400Regular',
    color: '#f1f5f8',
    fontSize: 21,
    lineHeight: 17,
    marginTop: 0,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.45)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 3,
  },
  accessPanel: {
    width: '95%',
    maxWidth: 360,
    borderWidth: 3,
    borderColor: '#b82a69',
    borderRadius: 14,
    backgroundColor: '#04090d',
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 7,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  accessCopy: {
    flex: 1,
    paddingRight: 8,
    paddingTop: 1,
  },
  accessPanelTitle: {
    fontFamily: 'Jersey10_400Regular',
    color: '#82f33e',
    fontSize: 38,
    lineHeight: 38,
    letterSpacing: 0.7,
    textAlignVertical: 'center',
  },
  accessPanelTitleDenied: {
    color: '#b9c1c7',
  },
  accessPanelDivider: {
    marginTop: 4,
    marginBottom: 6,
    height: 1,
    width: '100%',
    backgroundColor: 'rgba(213, 214, 219, 0.15)',
  },
  accessPanelText: {
    fontFamily: 'Jersey10_400Regular',
    color: '#f1f5f8',
    fontSize: 18,
    lineHeight: 20,
    letterSpacing: 1.1,
  },
  accessPanelTextDenied: {
    color: '#c4c8ce',
  },
  operatorSpriteWrap: {
    width: 82,
    height: 98,
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    marginLeft: 6,
  },
  operatorImage: {
    width: 78,
    height: 96,
  },
  bottomButtonsDock: {
    width: '95%',
    maxWidth: 360,
    marginTop: 8,
    paddingBottom: 8,
  },
  actionButtonWrapper: {
    width: '100%',
    marginTop: 0,
    paddingRight: BUTTON_SHADOW_OFFSET,
    paddingBottom: BUTTON_SHADOW_OFFSET,
  },
  actionButtonShadow: {
    position: 'absolute',
    top: BUTTON_SHADOW_OFFSET,
    left: BUTTON_SHADOW_OFFSET,
    right: 0,
    bottom: 0,
    backgroundColor: '#224614',
    borderRadius: 16,
  },
  actionButtonShadowDisabled: {
    backgroundColor: '#202428',
  },
  actionButtonPressable: {
    width: '100%',
  },
  actionButtonPressableDisabled: {
    opacity: 0.92,
  },
  actionButtonFace: {
    width: '100%',
    borderWidth: 3,
    borderColor: '#83f640',
    borderRadius: 16,
    backgroundColor: '#0d2608',
    height: 66,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonFaceDisabled: {
    borderColor: '#6d757d',
    backgroundColor: '#14181c',
  },
  actionButtonText: {
    fontFamily: 'Jersey10_400Regular',
    color: '#83f640',
    fontSize: 46,
    lineHeight: 46,
    letterSpacing: 1.2,
    textAlign: 'center',
    textAlignVertical: 'center',
    marginTop: 1,
    textShadowColor: 'rgba(131, 246, 64, 0.24)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  actionButtonTextDisabled: {
    color: '#8f979f',
    textShadowColor: 'rgba(0, 0, 0, 0)',
  },
  howToButtonWrapper: {
    marginTop: 8,
    maxWidth: 286,
    alignSelf: 'center',
  },
  howToButtonShadow: {
    backgroundColor: '#3b1d56',
    borderRadius: 10,
  },
  howToButtonFace: {
    borderColor: '#8f44c7',
    borderRadius: 10,
    backgroundColor: '#0b0820',
    height: 46,
    paddingVertical: 0,
  },
  howToButtonText: {
    color: '#d9c0ee',
    fontSize: 24,
    lineHeight: 24,
    letterSpacing: 1.2,
    textAlignVertical: 'center',
    marginTop: 1,
  },
  scanline: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: '#08140a',
  },
  scanlineOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  phosphorTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(35, 255, 55, 0.04)',
    zIndex: 1,
  },
  vignette: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.18)',
    zIndex: 1,
  },
});
