import { StyleSheet } from 'react-native';

export const onboardingStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#02060a',
  },
  loadingScreen: {
    flex: 1,
    backgroundColor: '#02060a',
  },
  content: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 2,
    paddingBottom: 14,
  },
  header: {
    marginBottom: 14,
    gap: 6,
  },
  stepMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  stepMetaText: {
    fontFamily: 'Jersey10_400Regular',
    color: '#b8cad6',
    fontSize: 24,
    lineHeight: 26,
    letterSpacing: 0.5,
  },
  progressBarTrack: {
    width: '100%',
    height: 8,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: 'rgba(44, 67, 84, 0.52)',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#7cf740',
  },
  stepShell: {
    flex: 1,
    borderWidth: 2,
    borderRadius: 18,
    borderColor: 'rgba(95, 140, 84, 0.72)',
    backgroundColor: 'rgba(6, 11, 15, 0.9)',
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 12,
    overflow: 'hidden',
  },
  sectionLabel: {
    fontFamily: 'Jersey10_400Regular',
    color: '#b8cad6',
    fontSize: 22,
    lineHeight: 24,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  promptText: {
    fontFamily: 'Jersey10_400Regular',
    color: '#f8fcff',
    fontSize: 40,
    lineHeight: 42,
    letterSpacing: 0.5,
    marginTop: 10,
  },
  helperText: {
    fontFamily: 'Jersey10_400Regular',
    color: '#d3e0e9',
    fontSize: 24,
    lineHeight: 26,
    letterSpacing: 0.35,
    marginTop: 8,
  },
  characterHelperText: {
    marginBottom: 14,
  },
  inputWrap: {
    marginTop: 18,
    borderWidth: 2,
    borderColor: '#5e7b8f',
    borderRadius: 14,
    backgroundColor: '#03080c',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  usernameInput: {
    fontFamily: 'Jersey10_400Regular',
    color: '#f8fcff',
    fontSize: 36,
    lineHeight: 40,
    letterSpacing: 0.55,
    minHeight: 54,
  },
  characterCounter: {
    marginTop: 10,
    textAlign: 'right',
    fontFamily: 'Jersey10_400Regular',
    color: '#b0c3d0',
    fontSize: 22,
    lineHeight: 24,
    letterSpacing: 0.6,
  },
  characterGrid: {
    marginTop: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 10,
  },
  characterCard: {
    width: '48.5%',
    borderWidth: 2,
    borderRadius: 14,
    borderColor: '#4f6f7e',
    backgroundColor: '#03080c',
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: 'center',
    minHeight: 120,
    justifyContent: 'center',
  },
  characterCardActive: {
    borderColor: '#82f33e',
    backgroundColor: '#0a170d',
  },
  characterImage: {
    width: 88,
    height: 88,
  },
  levelList: {
    marginTop: 14,
    paddingBottom: 8,
  },
  tierCard: {
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(136, 154, 171, 0.35)',
    borderRadius: 14,
    backgroundColor: 'rgba(9, 15, 20, 0.95)',
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 10,
  },
  tierTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  tierPill: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 3,
    marginRight: 10,
  },
  tierPillLabel: {
    fontFamily: 'Jersey10_400Regular',
    color: '#f2f7fb',
    fontSize: 22,
    lineHeight: 22,
    letterSpacing: 0.4,
  },
  tierRange: {
    fontFamily: 'Jersey10_400Regular',
    color: '#bdd0db',
    fontSize: 22,
    lineHeight: 24,
    letterSpacing: 0.4,
  },
  tierTitle: {
    fontFamily: 'Jersey10_400Regular',
    color: '#f8fcff',
    fontSize: 30,
    lineHeight: 32,
    letterSpacing: 0.5,
  },
  tierDescription: {
    marginTop: 3,
    fontFamily: 'Jersey10_400Regular',
    color: '#d9e5ed',
    fontSize: 23,
    lineHeight: 25,
    letterSpacing: 0.3,
  },
  tagRow: {
    marginTop: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  tagChip: {
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  tagLabel: {
    fontFamily: 'Jersey10_400Regular',
    color: '#f7fbff',
    fontSize: 18,
    lineHeight: 20,
    letterSpacing: 0.45,
  },
  footer: {
    marginTop: 12,
    gap: 8,
  },
  primaryButton: {
    width: '100%',
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#83f640',
    backgroundColor: '#0c2409',
    minHeight: 58,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  primaryButtonDisabled: {
    borderColor: '#5d6a74',
    backgroundColor: '#11181d',
  },
  primaryButtonText: {
    fontFamily: 'Jersey10_400Regular',
    color: '#83f640',
    fontSize: 34,
    lineHeight: 34,
    letterSpacing: 0.8,
    textAlign: 'center',
  },
  primaryButtonTextDisabled: {
    color: '#8a959d',
  },
  secondaryButton: {
    width: '100%',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#7d4fa7',
    backgroundColor: '#130a1d',
    minHeight: 46,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  secondaryButtonHidden: {
    opacity: 0,
  },
  secondaryButtonText: {
    fontFamily: 'Jersey10_400Regular',
    color: '#d7bfeb',
    fontSize: 25,
    lineHeight: 27,
    letterSpacing: 0.6,
  },
});
